#############################################################################
# Makefile for building: menu
# Generated by qmake (2.01a) (Qt 4.7.0) on: Wed Jan 26 14:35:14 2011
# Project:  menu.pro
# Template: app
# Command: /home/user/br2010.11/build/qt-everywhere-opensource-src-4.7.0/bin/qmake -o Makefile menu.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/share/renesas-4.4/bin/sh-linux-gnu-gcc
CXX           = /usr/share/renesas-4.4/bin/sh-linux-gnu-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = --sysroot=/home/user/br2010.11/build/staging_dir -pipe -O0 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = --sysroot=/home/user/br2010.11/build/staging_dir -pipe -O0 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../br2010.11/build/staging_dir/usr/mkspecs/qws/linux-sh-g++ -I. -I../../../br2010.11/build/staging_dir/usr/include/QtCore -I../../../br2010.11/build/staging_dir/usr/include/QtNetwork -I../../../br2010.11/build/staging_dir/usr/include/QtGui -I../../../br2010.11/build/staging_dir/usr/include -I.
LINK          = /usr/share/renesas-4.4/bin/sh-linux-gnu-g++ --sysroot=/home/user/br2010.11/build/staging_dir
LFLAGS        = -L/home/user/br2010.11/build/staging_dir/lib -L/home/user/br2010.11/build/staging_dir/usr/lib -Wl,-O1
LIBS          = $(SUBLIBS)  -L/home/user/br2010.11/build/staging_dir/usr/lib -lQtGui -L/home/user/br2010.11/build/staging_dir/usr/lib -ldirectfb -lfusion -ldirect -lQtNetwork -lQtCore -lpthread 
AR            = /usr/share/renesas-4.4/bin/sh-linux-gnu-ar cqs
RANLIB        = /usr/share/renesas-4.4/bin/sh-linux-gnu-ranlib
QMAKE         = /home/user/br2010.11/build/qt-everywhere-opensource-src-4.7.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = true
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		carousel.cpp \
		pixmap.cpp moc_carousel.cpp \
		moc_pixmap.cpp \
		qrc_menu.cpp
OBJECTS       = main.o \
		carousel.o \
		pixmap.o \
		moc_carousel.o \
		moc_pixmap.o \
		qrc_menu.o
DIST          = ../../../br2010.11/build/staging_dir/usr/mkspecs/common/g++.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/common/unix.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/common/linux.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/common/qws.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/qconfig.pri \
		../../../br2010.11/build/staging_dir/usr/mkspecs/modules/qt_webkit_version.pri \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt_functions.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt_config.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/exclusive_builds.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/default_pre.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/release.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/default_post.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/warn_on.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/unix/thread.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/moc.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/resources.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/uic.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/yacc.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/lex.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/include_source_dir.prf \
		menu.pro
QMAKE_TARGET  = menu
DESTDIR       = 
TARGET        = menu

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: menu.pro  ../../../br2010.11/build/staging_dir/usr/mkspecs/qws/linux-sh-g++/qmake.conf ../../../br2010.11/build/staging_dir/usr/mkspecs/common/g++.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/common/unix.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/common/linux.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/common/qws.conf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/qconfig.pri \
		../../../br2010.11/build/staging_dir/usr/mkspecs/modules/qt_webkit_version.pri \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt_functions.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt_config.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/exclusive_builds.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/default_pre.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/release.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/default_post.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/warn_on.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/unix/thread.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/moc.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/resources.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/uic.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/yacc.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/lex.prf \
		../../../br2010.11/build/staging_dir/usr/mkspecs/features/include_source_dir.prf \
		/home/user/br2010.11/build/staging_dir/usr/lib/libQtGui.prl \
		/home/user/br2010.11/build/staging_dir/usr/lib/libQtNetwork.prl \
		/home/user/br2010.11/build/staging_dir/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile menu.pro
../../../br2010.11/build/staging_dir/usr/mkspecs/common/g++.conf:
../../../br2010.11/build/staging_dir/usr/mkspecs/common/unix.conf:
../../../br2010.11/build/staging_dir/usr/mkspecs/common/linux.conf:
../../../br2010.11/build/staging_dir/usr/mkspecs/common/qws.conf:
../../../br2010.11/build/staging_dir/usr/mkspecs/qconfig.pri:
../../../br2010.11/build/staging_dir/usr/mkspecs/modules/qt_webkit_version.pri:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt_functions.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt_config.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/exclusive_builds.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/default_pre.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/release.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/default_post.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/warn_on.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/qt.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/unix/thread.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/moc.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/resources.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/uic.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/yacc.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/lex.prf:
../../../br2010.11/build/staging_dir/usr/mkspecs/features/include_source_dir.prf:
/home/user/br2010.11/build/staging_dir/usr/lib/libQtGui.prl:
/home/user/br2010.11/build/staging_dir/usr/lib/libQtNetwork.prl:
/home/user/br2010.11/build/staging_dir/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile menu.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/menu1.0.0 || $(MKDIR) .tmp/menu1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/menu1.0.0/ && $(COPY_FILE) --parents carousel.h pixmap.h .tmp/menu1.0.0/ && $(COPY_FILE) --parents menu.qrc .tmp/menu1.0.0/ && $(COPY_FILE) --parents main.cpp carousel.cpp pixmap.cpp .tmp/menu1.0.0/ && (cd `dirname .tmp/menu1.0.0` && $(TAR) menu1.0.0.tar menu1.0.0 && $(COMPRESS) menu1.0.0.tar) && $(MOVE) `dirname .tmp/menu1.0.0`/menu1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/menu1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_carousel.cpp moc_pixmap.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_carousel.cpp moc_pixmap.cpp
moc_carousel.cpp: carousel.h
	/home/user/br2010.11/build/staging_dir/usr/bin/moc $(DEFINES) $(INCPATH) carousel.h -o moc_carousel.cpp

moc_pixmap.cpp: pixmap.h
	/home/user/br2010.11/build/staging_dir/usr/bin/moc $(DEFINES) $(INCPATH) pixmap.h -o moc_pixmap.cpp

compiler_rcc_make_all: qrc_menu.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_menu.cpp
qrc_menu.cpp: menu.qrc \
		cog.png \
		qvga/cam.png \
		qvga/streaming.png \
		qvga/power.png \
		qvga/directfb.png \
		qvga/cam-play.png \
		qvga/movie-reel.png \
		qvga/slides.png
	/home/user/br2010.11/build/staging_dir/usr/bin/rcc -name menu menu.qrc -o qrc_menu.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: main.moc
compiler_moc_source_clean:
	-$(DEL_FILE) main.moc
main.moc: pixmap.h \
		carousel.h \
		main.cpp
	/home/user/br2010.11/build/staging_dir/usr/bin/moc $(DEFINES) $(INCPATH) main.cpp -o main.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_moc_source_clean 

####### Compile

main.o: main.cpp pixmap.h \
		carousel.h \
		main.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

carousel.o: carousel.cpp pixmap.h \
		carousel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carousel.o carousel.cpp

pixmap.o: pixmap.cpp pixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixmap.o pixmap.cpp

moc_carousel.o: moc_carousel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_carousel.o moc_carousel.cpp

moc_pixmap.o: moc_pixmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pixmap.o moc_pixmap.cpp

qrc_menu.o: qrc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_menu.o qrc_menu.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/root/ || $(MKDIR) $(INSTALL_ROOT)/root/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/root/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/root/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/root/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/root/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

